import { create, StoreApi, UseBoundStore } from "zustand";
import { rowById } from "./consts";
import { RowInfo, SelectionAction, SelectionState } from "./types";

export type SelectionStoreInstance = UseBoundStore<
  StoreApi<SelectionState & SelectionAction>
>;

// Helper to check if an ID is auto-generated by DataGrid grouping
const isAutoGeneratedId = (id: string) => id.startsWith("auto-generated-row-");

export function createSelectionStore(initialIds?: Set<string>) {
  return create<SelectionState & SelectionAction>((set, get) => ({
    maxTracks: 30,
    // Stores ALL selected IDs, including auto-generated group IDs
    selectedIds: initialIds ? new Set(initialIds) : new Set<string>(),
    // Returns only real track IDs (filters out auto-generated group IDs)
    getTrackIds: () => {
      const all = get().selectedIds;
      return new Set([...all].filter((id) => !isAutoGeneratedId(id)));
    },
    // Returns a Map of track IDs to RowInfo (no auto-generated IDs)
    getTrackMap: () => {
      const all = get().selectedIds;
      const map = new Map<string, RowInfo>();
      all.forEach((id) => {
        if (!isAutoGeneratedId(id)) {
          const row = rowById.get(id);
          if (row) {
            map.set(id, row);
          }
        }
      });
      return map;
    },
    setSelected: (ids: Set<string>) =>
      set(() => ({
        selectedIds: new Set(ids),
      })),
    removeIds: (removedIds: Set<string>) =>
      set((state) => {
        const next = new Set(state.selectedIds);
        removedIds.forEach((id) => {
          next.delete(id);
        });
        return { selectedIds: next };
      }),
    clear: () => set(() => ({ selectedIds: new Set<string>() })),
  }));
}
