import {
  bigBedModule,
  bigWigModule,
  bulkBedModule,
  methylCModule,
  transcriptModule,
} from "../../src/lib";

export const bigWigExample = bigWigModule.create({
  id: "dnase",
  title: "DNase aggregate",
  color: "#1B2021",
  height: 50,
  url: "https://downloads.wenglab.org/DNAse_All_ENCODE_MAR20_2024_merged.bw",
});

export const bigBedExample = bigBedModule.create({
  id: "astro-peaks",
  title: "Astro peaks",
  color: "#4b9560",
  display: "squish",
  height: 35,
  url: "https://downloads.wenglab.org/Astro.PeakCalls.bb",
  onClick: ({ item }) => {
    console.log(item.name);
  },
});

export const bulkBedExample = bulkBedModule.create({
  id: "chip-bulk-peaks",
  title: "bulk BigBed",
  color: "#db6d28",
  height: 30,
  gap: 2,
  datasets: [
    {
      name: "ChIP Dataset 1",
      url: "https://downloads.wenglab.org/ChIP_ENCSR000AKA-ENCSR000AKC-ENCSR000AKF-ENCSR000AKE-ENCSR000AKD-ENCSR000AOX.bigBed",
    },
    {
      name: "ChIP Dataset 2",
      url: "https://downloads.wenglab.org/ChIP_ENCSR000EWA-ENCSR000AKP-ENCSR000EWC-ENCSR000DWB-ENCSR000EWB-ENCSR000APE.bigBed",
    },
    {
      name: "ChIP Dataset 3",
      url: "https://downloads.wenglab.org/ChIP_ENCSR000ARA-ENCSR000AQW-ENCSR000AQY-ENCSR000AQX-ENCSR000ASX-ENCSR000ARZ.bigBed",
    },
  ],
  onClick: ({ item }) => {
    console.log(item.name);
  },
});

export const transcriptExample = transcriptModule.create({
  id: "genes",
  title: "Genes",
  assembly: "GRCh38",
  version: 40,
  geneName: "SOX4",
  display: "squish",
  color: "#7a4fb3",
  canonicalColor: "#d45c2f",
  highlightColor: "#1f77b4",
  height: 35,
  onClick: ({ item }) => {
    console.log(item.name);
  },
});

export const MOHDMethylC = methylCModule.create({
  id: "methylc",
  title: "MethylC Track",
  height: 100,
  colors: {
    cpg: "#648bd8",
    chg: "#ff944d",
    chh: "#ff00ff",
    depth: "#525252",
  },
  range: { min: 0, max: 1 },
  urls: {
    plusStrand: {
      cpg: {
        url: "https://users.wenglab.org/mezaj/mohd/EB100001/EB100001_cpg_pos.bw",
      },
      chg: {
        url: "https://users.wenglab.org/mezaj/mohd/EB100001/EB100001_chg_pos.bw",
      },
      chh: {
        url: "https://users.wenglab.org/mezaj/mohd/EB100001/EB100001_chh_pos.bw",
      },
      depth: {
        url: "https://users.wenglab.org/mezaj/mohd/EB100001/EB100001_coverage_pos.bw",
      },
    },
    minusStrand: {
      cpg: {
        url: "https://users.wenglab.org/mezaj/mohd/EB100001/EB100001_cpg_neg.bw",
      },
      chg: {
        url: "https://users.wenglab.org/mezaj/mohd/EB100001/EB100001_chg_neg.bw",
      },
      chh: {
        url: "https://users.wenglab.org/mezaj/mohd/EB100001/EB100001_chh_neg.bw",
      },
      depth: {
        url: "https://users.wenglab.org/mezaj/mohd/EB100001/EB100001_coverage_neg.bw",
      },
    },
  },
});

const phanh = "https://users.wenglab.org/phanh/PsychENCODE/hg38/";
export const MukamelMethylC = (name: MukamelMethylationName) =>
  methylCModule.create({
    id: name,
    title: "Mukamel " + name,
    height: 50,
    color: "#000000",
    colors: {
      cpg: "#648bd8",
      chg: "#ff944d",
      chh: "#ff00ff",
      depth: "#525252",
    },
    urls: {
      plusStrand: {
        cpg: {
          url:
            phanh + "data/Mukamel_2024/level3/" + name + ".CGN-Watson.frac.bw",
        },
        chg: {
          url:
            phanh + "data/Mukamel_2024/level3/" + name + ".CHN-Watson.frac.bw",
        },
        chh: { url: "" },
        depth: {
          url:
            phanh + "data/Mukamel_2024/level3/" + name + ".CGN-Watson.cov.bw",
        },
      },
      minusStrand: {
        cpg: {
          url:
            phanh + "data/Mukamel_2024/level3/" + name + ".CGN-Crick.frac.bw",
        },
        chg: {
          url:
            phanh + "data/Mukamel_2024/level3/" + name + ".CHN-Crick.frac.bw",
        },
        chh: { url: "" },
        depth: {
          url: phanh + "data/Mukamel_2024/level3/" + name + ".CGN-Crick.cov.bw",
        },
      },
    },
  });

export const mukamelMethylationNames = [
  "CGE_ADARB2_ADAM33",
  "CGE_ADARB2_ADAM33.female",
  "CGE_ADARB2_ADAM33.female.old",
  "CGE_ADARB2_ADAM33.female.young",
  "CGE_ADARB2_ADAM33.male",
  "CGE_ADARB2_ADAM33.male.old",
  "CGE_ADARB2_ADAM33.male.young",
  "CGE_ADARB2_ADAM33.old",
  "CGE_ADARB2_ADAM33.young",
  "CGE_LAMP5_FREM1",
  "CGE_LAMP5_FREM1.female",
  "CGE_LAMP5_FREM1.female.old",
  "CGE_LAMP5_FREM1.female.young",
  "CGE_LAMP5_FREM1.male",
  "CGE_LAMP5_FREM1.male.old",
  "CGE_LAMP5_FREM1.male.young",
  "CGE_LAMP5_FREM1.old",
  "CGE_LAMP5_FREM1.young",
  "CGE_LAMP5_LHX6",
  "CGE_LAMP5_LHX6.female",
  "CGE_LAMP5_LHX6.female.old",
  "CGE_LAMP5_LHX6.female.young",
  "CGE_LAMP5_LHX6.male",
  "CGE_LAMP5_LHX6.male.old",
  "CGE_LAMP5_LHX6.male.young",
  "CGE_LAMP5_LHX6.old",
  "CGE_LAMP5_LHX6.young",
  "CGE_LAMP5_NDNF",
  "CGE_LAMP5_NDNF.female",
  "CGE_LAMP5_NDNF.female.old",
  "CGE_LAMP5_NDNF.female.young",
  "CGE_LAMP5_NDNF.male",
  "CGE_LAMP5_NDNF.male.old",
  "CGE_LAMP5_NDNF.male.young",
  "CGE_LAMP5_NDNF.old",
  "CGE_LAMP5_NDNF.young",
  "CGE_PAX6",
  "CGE_PAX6.female",
  "CGE_PAX6.female.old",
  "CGE_PAX6.female.young",
  "CGE_PAX6.male",
  "CGE_PAX6.male.old",
  "CGE_PAX6.male.young",
  "CGE_PAX6.old",
  "CGE_PAX6.young",
  "CGE_VIP_DPF3",
  "CGE_VIP_DPF3.female",
  "CGE_VIP_DPF3.female.old",
  "CGE_VIP_DPF3.female.young",
  "CGE_VIP_DPF3.male",
  "CGE_VIP_DPF3.male.old",
  "CGE_VIP_DPF3.male.young",
  "CGE_VIP_DPF3.old",
  "CGE_VIP_DPF3.young",
  "CGE_VIP_FGD5",
  "CGE_VIP_FGD5.female",
  "CGE_VIP_FGD5.female.old",
  "CGE_VIP_FGD5.female.young",
  "CGE_VIP_FGD5.male",
  "CGE_VIP_FGD5.male.old",
  "CGE_VIP_FGD5.male.young",
  "CGE_VIP_FGD5.old",
  "CGE_VIP_FGD5.young",
  "CGE_VIP_ZBTB20",
  "CGE_VIP_ZBTB20.female",
  "CGE_VIP_ZBTB20.female.old",
  "CGE_VIP_ZBTB20.female.young",
  "CGE_VIP_ZBTB20.male",
  "CGE_VIP_ZBTB20.male.old",
  "CGE_VIP_ZBTB20.male.young",
  "CGE_VIP_ZBTB20.old",
  "CGE_VIP_ZBTB20.young",
  "Glia_Astro",
  "Glia_Astro.female",
  "Glia_Astro.female.old",
  "Glia_Astro.female.young",
  "Glia_Astro.male",
  "Glia_Astro.male.old",
  "Glia_Astro.male.young",
  "Glia_Astro.old",
  "Glia_Astro.young",
  "Glia_Micro",
  "Glia_Micro.female",
  "Glia_Micro.female.old",
  "Glia_Micro.female.young",
  "Glia_Micro.male",
  "Glia_Micro.male.old",
  "Glia_Micro.male.young",
  "Glia_Micro.old",
  "Glia_Micro.young",
  "Glia_Oligo",
  "Glia_Oligo.female",
  "Glia_Oligo.female.old",
  "Glia_Oligo.female.young",
  "Glia_Oligo.male",
  "Glia_Oligo.male.old",
  "Glia_Oligo.male.young",
  "Glia_Oligo.old",
  "Glia_Oligo.young",
  "L2-4IT_CUX2_LINC01331",
  "L2-4IT_CUX2_LINC01331.female",
  "L2-4IT_CUX2_LINC01331.female.old",
  "L2-4IT_CUX2_LINC01331.female.young",
  "L2-4IT_CUX2_LINC01331.male",
  "L2-4IT_CUX2_LINC01331.male.old",
  "L2-4IT_CUX2_LINC01331.male.young",
  "L2-4IT_CUX2_LINC01331.old",
  "L2-4IT_CUX2_LINC01331.young",
  "L3-5IT_RORB_PLCH1",
  "L3-5IT_RORB_PLCH1.female",
  "L3-5IT_RORB_PLCH1.female.old",
  "L3-5IT_RORB_PLCH1.female.young",
  "L3-5IT_RORB_PLCH1.male",
  "L3-5IT_RORB_PLCH1.male.old",
  "L3-5IT_RORB_PLCH1.male.young",
  "L3-5IT_RORB_PLCH1.old",
  "L3-5IT_RORB_PLCH1.young",
  "L4-5IT_RORB_ARHGAP15",
  "L4-5IT_RORB_ARHGAP15.female",
  "L4-5IT_RORB_ARHGAP15.female.old",
  "L4-5IT_RORB_ARHGAP15.female.young",
  "L4-5IT_RORB_ARHGAP15.male",
  "L4-5IT_RORB_ARHGAP15.male.old",
  "L4-5IT_RORB_ARHGAP15.male.young",
  "L4-5IT_RORB_ARHGAP15.old",
  "L4-5IT_RORB_ARHGAP15.young",
  "L4-5IT_RORB_GSN",
  "L4-5IT_RORB_GSN.female",
  "L4-5IT_RORB_GSN.female.old",
  "L4-5IT_RORB_GSN.female.young",
  "L4-5IT_RORB_GSN.male",
  "L4-5IT_RORB_GSN.male.old",
  "L4-5IT_RORB_GSN.male.young",
  "L4-5IT_RORB_GSN.old",
  "L4-5IT_RORB_GSN.young",
  "L4-5IT_RORB_TSHZ2",
  "L4-5IT_RORB_TSHZ2.female",
  "L4-5IT_RORB_TSHZ2.female.old",
  "L4-5IT_RORB_TSHZ2.female.young",
  "L4-5IT_RORB_TSHZ2.male",
  "L4-5IT_RORB_TSHZ2.male.old",
  "L4-5IT_RORB_TSHZ2.male.young",
  "L4-5IT_RORB_TSHZ2.old",
  "L4-5IT_RORB_TSHZ2.young",
  "L4-5IT_RORB_WHRN",
  "L4-5IT_RORB_WHRN.female",
  "L4-5IT_RORB_WHRN.female.old",
  "L4-5IT_RORB_WHRN.female.young",
  "L4-5IT_RORB_WHRN.male",
  "L4-5IT_RORB_WHRN.male.old",
  "L4-5IT_RORB_WHRN.male.young",
  "L4-5IT_RORB_WHRN.old",
  "L4-5IT_RORB_WHRN.young",
  "L56NP_TLE4_TSHZ2",
  "L56NP_TLE4_TSHZ2.female",
  "L56NP_TLE4_TSHZ2.female.old",
  "L56NP_TLE4_TSHZ2.female.young",
  "L56NP_TLE4_TSHZ2.male",
  "L56NP_TLE4_TSHZ2.male.old",
  "L56NP_TLE4_TSHZ2.male.young",
  "L56NP_TLE4_TSHZ2.old",
  "L56NP_TLE4_TSHZ2.young",
  "L5ET_FEZF2_ADRA1A",
  "L5ET_FEZF2_ADRA1A.female",
  "L5ET_FEZF2_ADRA1A.female.old",
  "L5ET_FEZF2_ADRA1A.female.young",
  "L5ET_FEZF2_ADRA1A.male",
  "L5ET_FEZF2_ADRA1A.male.old",
  "L5ET_FEZF2_ADRA1A.male.young",
  "L5ET_FEZF2_ADRA1A.old",
  "L5ET_FEZF2_ADRA1A.young",
  "L6CT_TLE4_FAM95C",
  "L6CT_TLE4_FAM95C.female",
  "L6CT_TLE4_FAM95C.female.old",
  "L6CT_TLE4_FAM95C.female.young",
  "L6CT_TLE4_FAM95C.male",
  "L6CT_TLE4_FAM95C.male.old",
  "L6CT_TLE4_FAM95C.male.young",
  "L6CT_TLE4_FAM95C.old",
  "L6CT_TLE4_FAM95C.young",
  "L6IT_THEMIS_CUX1",
  "L6IT_THEMIS_CUX1.female",
  "L6IT_THEMIS_CUX1.female.old",
  "L6IT_THEMIS_CUX1.female.young",
  "L6IT_THEMIS_CUX1.male",
  "L6IT_THEMIS_CUX1.male.old",
  "L6IT_THEMIS_CUX1.male.young",
  "L6IT_THEMIS_CUX1.old",
  "L6IT_THEMIS_CUX1.young",
  "L6IT_THEMIS_LINC00343",
  "L6IT_THEMIS_LINC00343.female",
  "L6IT_THEMIS_LINC00343.female.old",
  "L6IT_THEMIS_LINC00343.female.young",
  "L6IT_THEMIS_LINC00343.male",
  "L6IT_THEMIS_LINC00343.male.old",
  "L6IT_THEMIS_LINC00343.male.young",
  "L6IT_THEMIS_LINC00343.old",
  "L6IT_THEMIS_LINC00343.young",
  "L6b_TLE4_NXPH4",
  "L6b_TLE4_NXPH4.female",
  "L6b_TLE4_NXPH4.female.old",
  "L6b_TLE4_NXPH4.female.young",
  "L6b_TLE4_NXPH4.male",
  "L6b_TLE4_NXPH4.male.old",
  "L6b_TLE4_NXPH4.male.young",
  "L6b_TLE4_NXPH4.old",
  "L6b_TLE4_NXPH4.young",
  "MGE_PVALB_COL15A1",
  "MGE_PVALB_COL15A1.female",
  "MGE_PVALB_COL15A1.female.old",
  "MGE_PVALB_COL15A1.female.young",
  "MGE_PVALB_COL15A1.male",
  "MGE_PVALB_COL15A1.male.old",
  "MGE_PVALB_COL15A1.male.young",
  "MGE_PVALB_COL15A1.old",
  "MGE_PVALB_COL15A1.young",
  "MGE_PVALB_MYO5B",
  "MGE_PVALB_MYO5B.female",
  "MGE_PVALB_MYO5B.female.old",
  "MGE_PVALB_MYO5B.female.young",
  "MGE_PVALB_MYO5B.male",
  "MGE_PVALB_MYO5B.male.old",
  "MGE_PVALB_MYO5B.male.young",
  "MGE_PVALB_MYO5B.old",
  "MGE_PVALB_MYO5B.young",
  "MGE_SST_CDH12",
  "MGE_SST_CDH12.female",
  "MGE_SST_CDH12.female.old",
  "MGE_SST_CDH12.female.young",
  "MGE_SST_CDH12.male",
  "MGE_SST_CDH12.male.old",
  "MGE_SST_CDH12.male.young",
  "MGE_SST_CDH12.old",
  "MGE_SST_CDH12.young",
  "MGE_SST_CLMP",
  "MGE_SST_CLMP.female",
  "MGE_SST_CLMP.female.old",
  "MGE_SST_CLMP.female.young",
  "MGE_SST_CLMP.male",
  "MGE_SST_CLMP.male.old",
  "MGE_SST_CLMP.male.young",
  "MGE_SST_CLMP.old",
  "MGE_SST_CLMP.young",
  "MGE_SST_NPY",
  "MGE_SST_NPY.female",
  "MGE_SST_NPY.female.old",
  "MGE_SST_NPY.female.young",
  "MGE_SST_NPY.male",
  "MGE_SST_NPY.male.old",
  "MGE_SST_NPY.male.young",
  "MGE_SST_NPY.old",
  "MGE_SST_NPY.young",
  "MGE_SST_RAB31",
  "MGE_SST_RAB31.female",
  "MGE_SST_RAB31.female.old",
  "MGE_SST_RAB31.female.young",
  "MGE_SST_RAB31.male",
  "MGE_SST_RAB31.male.old",
  "MGE_SST_RAB31.male.young",
  "MGE_SST_RAB31.old",
  "MGE_SST_RAB31.young",
] as const;

export type MukamelMethylationName = (typeof mukamelMethylationNames)[number];
