table bigGenePredPlusV1
"Version 1 transcript annotations for indexed genome-browser rendering"
(
    string chrom;                   "Reference chromosome"
    uint chromStart;                "Zero-based transcript start"
    uint chromEnd;                  "Half-open transcript end"
    string name;                    "Versioned transcript identifier"
    uint score;                     "BED score from 0 through 1000"
    char[1] strand;                 "Transcript strand"
    uint thickStart;                "Zero-based CDS start"
    uint thickEnd;                  "Half-open CDS end"
    uint reserved;                  "Item RGB"
    int blockCount;                 "Number of exons"
    int[blockCount] blockSizes;     "Exon sizes in genomic order"
    int[blockCount] chromStarts;    "Exon starts relative to chromStart"
    string name2;                   "Human-readable transcript name"
    string cdsStartStat;            "none, unk, incmpl, or cmpl"
    string cdsEndStat;              "none, unk, incmpl, or cmpl"
    int[blockCount] exonFrames;     "CDS frame in transcription order, or -1"
    string type;                    "Transcript type"
    string geneName;                "Versioned stable gene identifier"
    string geneName2;               "Human-readable gene name"
    string geneType;                "Gene type"
    string tags;                    "Comma-separated transcript tags"
    lstring attributes;             "Compact JSON containing remaining transcript attributes"
)
